{"name": "НЕ успешная аутентификация с неверным логином и паролем", "status": "passed", "start": 1724853870944, "stop": 1724853871172, "uuid": "db7c792b-a7be-4f2d-afb9-a4ccb1ddd9df", "historyId": "c4e089a9902cd53144313564fea0b221", "testCaseId": "c4e089a9902cd53144313564fea0b221", "fullName": "tests.test_login_user.TestAuthentication#test_auth_with_invalid_password_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestAuthentication"}, {"name": "host", "value": "Lex_Legion"}, {"name": "thread", "value": "30608-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}